import { config } from "dotenv";
config({ path: ".env.local" });

import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { agents } from "@/server/db/schema";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const SEED_AGENTS = [
  {
    name: "Claude Code",
    slug: "claude-code",
    description: "Autonomous coding agent by Anthropic. Reads, writes, and debugs code across entire codebases.",
    longDescription: "Claude Code is Anthropic's CLI-based coding agent that can autonomously navigate codebases, write and edit files, run tests, and handle complex multi-step development tasks. It understands project context deeply and can make coordinated changes across many files.",
    category: "Coding",
    provider: "Anthropic",
    websiteUrl: "https://claude.ai",
    githubUrl: "https://github.com/anthropics/claude-code",
    avgCostPerRun: "0.12",
    permissionsRequired: ["filesystem", "network", "shell"],
    trustScore: "4.60",
    totalReviews: 2341,
    totalUpvotes: 1247,
    isVerified: true,
    isFeatured: true,
    tags: ["coding", "cli", "autonomous", "debugging", "refactoring"],
  },
  {
    name: "Cursor Agent",
    slug: "cursor-agent",
    description: "AI-powered code editor agent. Context-aware completions and multi-file editing with deep codebase understanding.",
    longDescription: "Cursor is an AI-first code editor built on VS Code. Its agent mode can plan and execute multi-step coding tasks, understand your entire project context, and make intelligent edits across multiple files simultaneously.",
    category: "Coding",
    provider: "Cursor",
    websiteUrl: "https://cursor.com",
    avgCostPerRun: "0.08",
    permissionsRequired: ["filesystem", "network"],
    trustScore: "4.80",
    totalReviews: 1823,
    totalUpvotes: 987,
    isVerified: true,
    isFeatured: true,
    tags: ["coding", "editor", "ide", "autocomplete", "multi-file"],
  },
  {
    name: "Perplexity Deep Research",
    slug: "perplexity-research",
    description: "Deep web research agent. Multi-step search, source verification, and comprehensive report generation.",
    longDescription: "Perplexity's Deep Research mode conducts thorough multi-step research across the web, verifying sources, cross-referencing information, and generating comprehensive reports with citations. Great for due diligence, market research, and technical investigations.",
    category: "Research",
    provider: "Perplexity",
    websiteUrl: "https://perplexity.ai",
    avgCostPerRun: "0.05",
    permissionsRequired: ["network"],
    trustScore: "4.30",
    totalReviews: 945,
    totalUpvotes: 623,
    isVerified: true,
    isFeatured: false,
    tags: ["research", "search", "citations", "reports", "web"],
  },
  {
    name: "Devin",
    slug: "devin",
    description: "Fully autonomous software engineer. Plans, codes, tests, and deploys complete features independently.",
    longDescription: "Devin by Cognition Labs is a fully autonomous software engineer that can plan entire feature implementations, write code, set up environments, run tests, debug issues, and even deploy — all independently with minimal human guidance.",
    category: "Coding",
    provider: "Cognition",
    websiteUrl: "https://devin.ai",
    avgCostPerRun: "2.50",
    permissionsRequired: ["filesystem", "network", "shell", "docker"],
    trustScore: "3.90",
    totalReviews: 1567,
    totalUpvotes: 445,
    isVerified: true,
    isFeatured: false,
    tags: ["coding", "autonomous", "full-stack", "deployment", "testing"],
  },
  {
    name: "GPT Researcher",
    slug: "gpt-researcher",
    description: "Open-source autonomous research agent. Generates detailed reports from multiple web sources with citations.",
    longDescription: "GPT Researcher is an open-source agent that autonomously conducts comprehensive research on any topic. It generates long-form reports by scraping and synthesizing information from 20+ web sources, complete with proper citations and source verification.",
    category: "Research",
    provider: "Community",
    websiteUrl: "https://gptr.dev",
    githubUrl: "https://github.com/assafelovic/gpt-researcher",
    avgCostPerRun: "0.15",
    permissionsRequired: ["network"],
    trustScore: "4.10",
    totalReviews: 678,
    totalUpvotes: 412,
    isVerified: false,
    isFeatured: false,
    tags: ["research", "open-source", "reports", "web-scraping", "citations"],
  },
  {
    name: "v0 by Vercel",
    slug: "v0-vercel",
    description: "AI UI generator. Describe interfaces in natural language, get production-ready React + Tailwind code instantly.",
    longDescription: "v0 is Vercel's generative UI tool that converts natural language descriptions into polished, production-ready React components using Tailwind CSS and shadcn/ui. It can generate full page layouts, complex forms, dashboards, and interactive components.",
    category: "Design",
    provider: "Vercel",
    websiteUrl: "https://v0.dev",
    avgCostPerRun: "0.10",
    permissionsRequired: ["network"],
    trustScore: "4.50",
    totalReviews: 1456,
    totalUpvotes: 892,
    isVerified: true,
    isFeatured: true,
    tags: ["design", "ui", "react", "tailwind", "frontend", "generative"],
  },
  {
    name: "Windsurf (Codeium)",
    slug: "windsurf",
    description: "AI-powered IDE with Cascade agent. Deep codebase awareness, multi-file edits, and terminal integration.",
    longDescription: "Windsurf by Codeium is an AI-native IDE featuring the Cascade agent — a deep reasoning engine that understands your entire codebase, can make multi-file edits, run terminal commands, and manage complex refactoring tasks with full project context.",
    category: "Coding",
    provider: "Codeium",
    websiteUrl: "https://codeium.com/windsurf",
    avgCostPerRun: "0.06",
    permissionsRequired: ["filesystem", "network", "shell"],
    trustScore: "4.40",
    totalReviews: 1102,
    totalUpvotes: 734,
    isVerified: true,
    isFeatured: false,
    tags: ["coding", "ide", "editor", "cascade", "codebase-aware"],
  },
  {
    name: "Bolt.new",
    slug: "bolt-new",
    description: "Full-stack web app generator. Describe your app, get a running project with frontend, backend, and database.",
    longDescription: "Bolt.new by StackBlitz generates complete full-stack web applications from natural language descriptions. It sets up frontend, backend, database schemas, and deployment configuration — producing a running app in a WebContainer that you can iterate on.",
    category: "Coding",
    provider: "StackBlitz",
    websiteUrl: "https://bolt.new",
    avgCostPerRun: "0.20",
    permissionsRequired: ["filesystem", "network"],
    trustScore: "4.20",
    totalReviews: 867,
    totalUpvotes: 534,
    isVerified: true,
    isFeatured: false,
    tags: ["coding", "full-stack", "generator", "web-app", "rapid-prototyping"],
  },
  {
    name: "Lovable",
    slug: "lovable",
    description: "AI full-stack engineer. Build production-ready web apps with natural language — design, code, and deploy.",
    longDescription: "Lovable (formerly GPT Engineer) is an AI full-stack engineer that can build complete production-ready web applications from natural language prompts. It handles UI design, frontend code, backend logic, database setup, and deployment.",
    category: "Coding",
    provider: "Lovable",
    websiteUrl: "https://lovable.dev",
    avgCostPerRun: "0.25",
    permissionsRequired: ["filesystem", "network"],
    trustScore: "4.00",
    totalReviews: 645,
    totalUpvotes: 378,
    isVerified: true,
    isFeatured: false,
    tags: ["coding", "full-stack", "web-app", "design", "deployment"],
  },
  {
    name: "Jasper AI",
    slug: "jasper-ai",
    description: "Enterprise writing agent. Blog posts, marketing copy, social media content with brand voice matching.",
    longDescription: "Jasper is an enterprise AI writing platform that generates marketing copy, blog posts, social media content, and business communications. It can match your brand voice, follow style guides, and produce content across 30+ languages.",
    category: "Writing",
    provider: "Jasper",
    websiteUrl: "https://jasper.ai",
    avgCostPerRun: "0.03",
    permissionsRequired: ["network"],
    trustScore: "4.00",
    totalReviews: 534,
    totalUpvotes: 289,
    isVerified: true,
    isFeatured: false,
    tags: ["writing", "marketing", "content", "copywriting", "brand-voice"],
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    description: "AI image generation via Discord. Create stunning art, illustrations, and photorealistic images from text prompts.",
    longDescription: "Midjourney is a leading AI image generator accessible through Discord. It creates stunning photorealistic images, artistic illustrations, concept art, and design assets from text descriptions. Known for its exceptional aesthetic quality.",
    category: "Design",
    provider: "Midjourney",
    websiteUrl: "https://midjourney.com",
    avgCostPerRun: "0.04",
    permissionsRequired: ["network"],
    trustScore: "4.70",
    totalReviews: 3210,
    totalUpvotes: 2156,
    isVerified: true,
    isFeatured: true,
    tags: ["design", "image-generation", "art", "creative", "photorealistic"],
  },
  {
    name: "AutoGPT",
    slug: "autogpt",
    description: "Open-source autonomous AI agent. Chain multiple GPT-4 calls to accomplish complex tasks independently.",
    longDescription: "AutoGPT is an open-source autonomous AI agent that chains multiple LLM calls together to break down and accomplish complex tasks. It can browse the web, manage files, execute code, and self-correct — all with minimal human intervention.",
    category: "Automation",
    provider: "Community",
    websiteUrl: "https://agpt.co",
    githubUrl: "https://github.com/Significant-Gravitas/AutoGPT",
    avgCostPerRun: "0.50",
    permissionsRequired: ["filesystem", "network", "shell"],
    trustScore: "3.50",
    totalReviews: 2100,
    totalUpvotes: 890,
    isVerified: false,
    isFeatured: false,
    tags: ["automation", "autonomous", "open-source", "multi-step", "agent"],
  },
  {
    name: "CrewAI",
    slug: "crewai",
    description: "Multi-agent orchestration framework. Define teams of AI agents with roles, goals, and collaboration patterns.",
    longDescription: "CrewAI is a framework for orchestrating multiple AI agents working together. You define agent roles, goals, and backstories, then let them collaborate on complex tasks — from research to content creation to code review — with built-in task delegation.",
    category: "Automation",
    provider: "Community",
    websiteUrl: "https://crewai.com",
    githubUrl: "https://github.com/crewAIInc/crewAI",
    avgCostPerRun: "0.30",
    permissionsRequired: ["network"],
    trustScore: "4.20",
    totalReviews: 789,
    totalUpvotes: 567,
    isVerified: false,
    isFeatured: false,
    tags: ["automation", "multi-agent", "orchestration", "framework", "collaboration"],
  },
  {
    name: "ElevenLabs Voice Agent",
    slug: "elevenlabs-voice",
    description: "Conversational AI voice agent. Natural-sounding voice synthesis with real-time dialogue capabilities.",
    longDescription: "ElevenLabs' Voice Agent provides ultra-realistic voice synthesis and real-time conversational AI capabilities. It can handle phone calls, customer support, and interactive voice experiences with near-human quality speech in 29+ languages.",
    category: "Automation",
    provider: "ElevenLabs",
    websiteUrl: "https://elevenlabs.io",
    avgCostPerRun: "0.08",
    permissionsRequired: ["network", "audio"],
    trustScore: "4.50",
    totalReviews: 1034,
    totalUpvotes: 756,
    isVerified: true,
    isFeatured: false,
    tags: ["voice", "speech", "conversational", "tts", "real-time"],
  },
  {
    name: "Replit Agent",
    slug: "replit-agent",
    description: "AI coding agent in the cloud. Build, run, and deploy apps entirely from natural language instructions.",
    longDescription: "Replit Agent is a cloud-based AI coding assistant that can build entire applications from scratch. It handles project setup, code writing, dependency management, debugging, and deployment — all within Replit's cloud IDE environment.",
    category: "Coding",
    provider: "Replit",
    websiteUrl: "https://replit.com",
    avgCostPerRun: "0.15",
    permissionsRequired: ["filesystem", "network", "shell"],
    trustScore: "4.10",
    totalReviews: 923,
    totalUpvotes: 501,
    isVerified: true,
    isFeatured: false,
    tags: ["coding", "cloud", "deployment", "full-stack", "repl"],
  },
];

async function seed() {
  console.log("Seeding agents...");

  for (const agent of SEED_AGENTS) {
    try {
      await db.insert(agents).values(agent).onConflictDoNothing();
      console.log(`  ✓ ${agent.name}`);
    } catch (err) {
      console.error(`  ✗ ${agent.name}:`, err);
    }
  }

  console.log(`\nDone! Seeded ${SEED_AGENTS.length} agents.`);
}

seed().catch(console.error);
